import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import ThemeCompo from "./components/ThemeCompo";
import { ThemeProvider } from "next-themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Mankind website",
  description: "Generated by Mankind4dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <ThemeCompo>
            <Header />
            {children}
          </ThemeCompo>
        </ThemeProvider>
      </body>
    </html>
  );
}
